[project]
name = "connect4"
version = "0.1.0"
description = "Connect 4 Game with Reinforcement Learning"
authors = [
    { name = "Mario Reyes Ojeda", email = "m.reyeso@uniandes.edu.co" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "pygame>=2.6.1",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.34.0",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "pre-commit>=4.0.0",
    "pytest>=9.0.2",
    "ty>=0.0.1a7",
]

[tool.ty.rules]
possibly-unresolved-reference = "warn"

[tool.pytest.ini_options]
testpaths = ["tests"]
