services:
  - type: web
    name: connect4-game
    runtime: docker
    plan: free
    envVars:
      - key: Q_TABLE_PATH
        value: q_table.pkl
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: connect4-db
          property: connectionString

databases:
  - name: connect4-db
    plan: free
